export const INITIALIZE_APP = "INITIALIZE_APP";
export const SET_PROGRESS_LOADING = "SET_PROGRESS_LOADING";

export const SET_VALUE_ENTRY_FIELD = "SET_VALUE_ENTRY_FIELD";
export const SET_ENTRY_FIELD = "SET_ENTRY_FIELD";
export const SET_OUTPUT_FIELD = "SET_OUTPUT_FIELD";
export const SET_PAY_METHODS = "SET_PAY_METHODS";
export const SET_USER_EVENT = "SET_USER_EVENT";
export const SET_EXCHANGE_AMOUNT = "SET_EXCHANGE_AMOUNT";
